### PR TITLE
Allow defaults to be passed in to the form

### PR DESCRIPTION
**Pull request by bjpirt**
This very minor change initialises the default hurl with params instead of {} so that we can pass some values in and pre-populate the fields. This makes it a lot easier to send people examples of how to use an API call.

For example:

http://hurl.it/?url=http%3A%2F%2Fapi.pachube.com%2Ffeeds.json&header-keys[]=X-PachubeApiKey&header-vals[]=dshajfbds&method=POST&post-body=%3Csome%3E%0A%20%20%3Ccontent%3E%0A%20%20%3C%2Fcontent%3E%0A%3C%2Fsome%3E%0A

(if this were running on hurl.it of course)

Resubmitted to twilio/hurl instead of defunkt/hurl

### CODE REVIEW

**Comment by johnsheehan** [comment]
Before I pull this in, I just want to do a sanity check and ask if you know if this will lead to any CSRF or other injection issues. How safe is this?

**Comment by bjpirt** [comment]
I was wondering that as well, but Rails escapes all of the content before writing it back to the browser which should avoid any injection issues. e.g.

http://hurl.it/?url=my_url&method=POST&post-body=%3C/textarea%3E&header-keys[]=one&header-vals[]=%22%3E%3Cscript%3Ealert('hello')%3C/script%3E

**Comment by bjpirt** [comment]
I was asked to re-submit this here but it looks like it's just being ignored. Are you guys going to respond? Is twilio in charge of hurl now?

**Comment by johnsheehan** [comment]
it's live on hurl.it too

**Comment by bjpirt** [comment]
Sweet! Thanks.

**Pull request merged**
