### PR TITLE
add support for the PATCH http method 

### PR DESCRIPTION
**Pull request by igorw**

### CODE REVIEW

**Comment by avalanche123** [comment]
this looks good to me :+1:

**Comment by stevegraham** [comment]
I have two problems with PATCH:
1. It's completely unnecessary. The authors of RFC5789 are completely wrong about their interpretation of RFC2616. PUT does not require a complete replacement of the entire resource at all. See my comments on https://github.com/rails/rails/pull/505 for more details.
2. RFC5789 is merely a proposed standard, the least level of maturity for an IETF standard. It's barely a year old, which is not enough time for its flaws to be highlighted.

**Comment by igorw** [comment]
It doesn't cost much to add it and there are APIs out there that use it. Yes, PUT can be used as PATCH, so it's kind of pointless.

I don't really care if this gets merged either way. If you're just going to end up arguing over it, please just close it. ;)

**Comment by igorw** [comment]
Since it is not going to get merged, I'm closing this PR.

**Pull request closed without merging**
